name: CI/CD Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar verificação (CI)
        run: echo "CI executado com sucesso!"

      - name: Simular deploy (CD)
        run: echo "Deploy automatizado simulado com sucesso!"

  test-and-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        id: run_tests
        run: |
          pytest tests/

      - name: Send Discord Notification
        if: always()
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            MESSAGE="✅ Testes passaram no GitHub Actions!"
          else
            MESSAGE="❌ Testes falharam no GitHub Actions!"
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"$MESSAGE\"}" \
            "${{ secrets.DISCORD_WEBHOOK }}"
