name: Run Python Tests and Send Discord Alert

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      id: run_tests
      run: |
        pytest

    - name: Send Discord Notification
      if: always()
      run: |
        if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
          MESSAGE="✅ Testes passaram no GitHub Actions!"
        else
          MESSAGE="❌ Testes falharam no GitHub Actions!"
        fi

        curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"$MESSAGE\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"
