name: CI/CD Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Exemplo de execução
        run: echo "Rodando testes ou build (CI)"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulando Deploy
        run: echo "Fazendo deploy (CD)"

  test-and-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Rodar testes
        id: run_tests
        run: |
          pytest tests/

      - name: Enviar notificação para Discord
        if: always()
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            MESSAGE="✅ Testes passaram no GitHub Actions!"
          else
            MESSAGE="❌ Testes falharam no GitHub Actions!"
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"$MESSAGE\"}" \
            "${{ secrets.DISCORD_WEBHOOK }}"
