name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Exemplo de execução
        run: echo "Rodando testes ou build (CI)"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulando Deploy
        run: echo "Fazendo deploy (CD)"
