name: CI/CD Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar exemplo de execução
        run: echo "✅ Rodando testes ou build (CI)"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simular deploy
        run: echo "🚀 Fazendo deploy (CD)"

  test-and-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Rodar testes
        id: run_tests
        run: |
          export PYTHONPATH=$(pwd)
          pytest tests/

      - name: Enviar notificação para o Discord
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TEST_RESULT: ${{ steps.run_tests.outcome }}
        run: |
          if [ "$TEST_RESULT" = "success" ]; then
            MESSAGE="✅ Testes passaram no GitHub Actions!"
          else
            MESSAGE="❌ Testes falharam no GitHub Actions!"
          fi

          echo "Enviando mensagem: $MESSAGE"

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"$MESSAGE\"}" \
            "$DISCORD_WEBHOOK"
